### ISSUE TITLE
巴哈姆特和推特的数据源采集失败

### ISSUE THREAD

**Issue by SanaChitose** [Cosmos01/ba_calendar#1]
大佬考虑转发或者增加设置代理选项吗！

**Comment by Cosmos01** [comment]
我是用Proxifier来管理代理的，比每个插件配过去来的方便。
看了一下推特的sdk，创建client没有代理参数，如果要加只能全局或者换成api形式，前者可能对其他插件有影响，后者所有代码都要改，所以暂时不考虑添加了。

**Comment by SanaChitose** [comment]
好的 感谢大佬
